### ISSUE TITLE
Lumi causes the Dynamic Lights to fail

### ISSUE THREAD

**Issue by Omgise** [GTMEGA/LUMINA#3]
The torch does not emit light in my hand.

**Comment by FalsePattern** [comment]
Which dynamic lights mod?

**Comment by Omgise** [comment]
https://www.curseforge.com/minecraft/mc-mods/dynamic-lights

**Comment by FalsePattern** [comment]
Try it with FalseTweaks 3.3.0, i've implemented my own dynamic lights support that should be more compatible than the DynamicLights mod.

**Comment by Omgise** [comment]
Yes, your dynamic lights implementation performs better and is more effective.
